import env
import model

NUM_WORKERS = 1
MAX_FRAMES = 10000
GAME = env.CartPole
MODEL = model.CartPole
ENTRPOY_BETA = 0.01
MAX_ROLL_OUT = 5
GAMMA = 0.99
GRAD_CLIP_NORM = 40.0
INITIAL_LEARNING_RATE = 5e-4
LEARNING_RATE_DECAY = 0.96
MAX_STEPS = 1e4
