import env
import model

NUM_WORKERS = 3
GAME = env.CartPole
MODEL = model.CartPole
ENTROPY_BETA = 0.01
MAX_ROLL_OUT = 5
GAMMA = 0.99
GRAD_CLIP_NORM = 40.0
INITIAL_LEARNING_RATE = 0.01
LEARNING_RATE_DECAY = 0.5
MAX_STEPS = 1e5
